# Generated by Django 4.2 on 2024-12-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='short_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
