# Generated by Django 4.2 on 2024-12-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_shortenedurl_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
